source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/BJ_DEV/ZL_CommonSpec.git'

use_frameworks!

platform :ios, '8.0'

target 'ZLGuidePageView_Example' do
  pod 'ZLGuidePageView', :path => '../'
end

