use_frameworks!

platform :ios, '8.0'

target 'ZLGuidePageView_Example' do
  pod 'ZLGuidePageView', :path => '../'

  target 'ZLGuidePageView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
